CREATE TABLE IF NOT EXISTS `packs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nom` VARCHAR(255) NOT NULL,
  `description` TEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pack_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `pack_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  `quantite` INT NOT NULL DEFAULT 1,
  FOREIGN KEY (`pack_id`) REFERENCES `packs`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`article_id`) REFERENCES `products`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
